#!/bin/bash
# ═══════════════════════════════════════════════════════════════════
#  zsh-setup — ZSH + oh-my-zsh + powerlevel10k bootstrapper
#  ═══════════════════════════════════════════════════════════════════
#  Installs and configures a complete ZSH environment:
#    - ZSH shell (via pacman)
#    - oh-my-zsh framework
#    - powerlevel10k theme + auto-generated config
#    - ~/.zshrc (sources aliasmanager.sh + .zshconfig + .p10k.zsh)
#    - ~/.zshconfig (PATH, EDITOR, HISTORY, Android SDK, Flutter, Chrome)
#
#  USAGE:
#    bash zsh-setup.sh              # Run interactively
#    bash zsh-setup.sh --yes        # Run non-interactively
#    bash zsh-setup.sh --help       # Show help
#  ═══════════════════════════════════════════════════════════════════

set -eo pipefail

# ─── Colors ──────────────────────────────────────────────────────
R='\033[0;31m' G='\033[0;32m' Y='\033[1;33m' C='\033[0;36m'
B='\033[1;37m' N='\033[0m'

info()  { echo -e "  ${C}ℹ️${N}  $1"; }
ok()    { echo -e "  ${G}✅${N} $1"; }
warn()  { echo -e "  ${Y}⚠️${N}  $1"; }
fail()  { echo -e "  ${R}❌${N} $1"; }

prompt_yes() {
  local d="${2:-y}"
  printf "  %s [%s]: " "$1" "$d"
  read -r r
  r="${r:-$d}"
  [ "$r" = "y" ] || [ "$r" = "Y" ] || [ "$r" = "yes" ]
}

# ═══════════════════════════════════════════════════════════════════
#  ZSH-SETUP
#  ═══════════════════════════════════════════════════════════════════

setup_zsh() {
  echo ""
  echo "╔══════════════════════════════════════════════════════╗"
  echo "║            ZSH Setup — main4-plasma                 ║"
  echo "╚══════════════════════════════════════════════════════╝"

  # ── 1. Install ZSH ─────────────────────────────────────────
  echo ""
  info "Installing ZSH..."
  if command -v zsh &>/dev/null; then
    ok "ZSH already installed ($(zsh --version 2>/dev/null | head -1))"
  else
    sudo pacman -Syy --noconfirm
    sudo pacman -S --noconfirm zsh 2>&1 | tail -1
    ok "ZSH installed"
  fi

  # ── 2. Install oh-my-zsh ───────────────────────────────────
  echo ""
  info "Setting up oh-my-zsh..."
  if [ -d "$HOME/.oh-my-zsh" ]; then
    ok "oh-my-zsh already installed"
  else
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended 2>/dev/null
    if [ -d "$HOME/.oh-my-zsh" ]; then
      ok "oh-my-zsh installed"
    else
      fail "oh-my-zsh installation failed"
      return 1
    fi
  fi

  # ── 3. Install powerlevel10k ───────────────────────────────
  echo ""
  info "Setting up powerlevel10k theme..."
  local p10k_dir="$HOME/.oh-my-zsh/custom/themes/powerlevel10k"
  if [ -d "$p10k_dir" ]; then
    ok "powerlevel10k already installed"
  else
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$p10k_dir" 2>/dev/null
    if [ -d "$p10k_dir" ]; then
      ok "powerlevel10k installed"
    else
      warn "powerlevel10k installation failed — skipping"
    fi
  fi

  # ── 3b. Auto-generate .p10k.zsh (skip wizard forever) ─────
  echo ""
  info "Generating ~/.p10k.zsh..."
  cat > "$HOME/.p10k.zsh" <<'P10KEOF'
# Generated by zsh-setup.sh — powerlevel10k config
# Run 'p10k configure' to customize interactively.

POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

# Left prompt segments
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir vcs)
# Right prompt segments
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs time)

# Dir: show full path, shorten home to ~
POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
POWERLEVEL9K_DIR_MAX_LENGTH=30

# VCS (Git) — show branch, dirty, ahead/behind
POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=false
POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1
POWERLEVEL9K_VCS_SHOW_SUBMODULE_DIRTY=true
POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
POWERLEVEL9K_VCS_UNSTAGED_ICON='!'
POWERLEVEL9K_VCS_STAGED_ICON='+'
POWERLEVEL9K_VCS_STASH_ICON='*'
POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\u2BC4'
POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\u2BC6'

# Status — show exit code if non-zero
POWERLEVEL9K_STATUS_EXTENDED_STATES=true
POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_STATUS_ERROR=true
POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='\u2718'

# Time — 24h format
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M:%S}'
POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=true

# Prompt character — green for normal, red for root
POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION='\u276F'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION='\u276F'
POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=2
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=1

# Icons
POWERLEVEL9K_OS_ICON_BACKGROUND=15
POWERLEVEL9K_OS_ICON_FOREGROUND=0
POWERLEVEL9K_DIR_FOREGROUND=12
POWERLEVEL9K_DIR_BACKGROUND=15

# Separator style
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'
POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B1'
POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B3'
P10KEOF
  ok "~/.p10k.zsh generated (wizard disabled)"

  # ── 4. Generate .zshrc ─────────────────────────────────────
  echo ""
  info "Setting up ~/.zshrc..."

  # Handle existing .zshrc
  if [ -f "$HOME/.zshrc" ]; then
    if [ "${1:-}" != "--yes" ]; then
      if prompt_yes "Existing .zshrc found. Back it up and overwrite?" "y"; then
        local bak="$HOME/.zshrc.bak.$(date +%Y%m%d-%H%M%S)"
        cp "$HOME/.zshrc" "$bak"
        warn "Backed up -> $bak"
      else
        info "Skipping .zshrc"
        return 0
      fi
    else
      local bak="$HOME/.zshrc.bak.$(date +%Y%m%d-%H%M%S)"
      cp "$HOME/.zshrc" "$bak"
      warn "Backed up existing .zshrc -> $bak"
    fi
  fi

  # Find aliasmanager.sh (use $0 for zsh compatibility)
  local aliasman_path
  local script_dir
  script_dir="$(cd "$(dirname "$0")" && pwd)" || script_dir="$PWD"
  if [ -f "$script_dir/aliasmanager.sh" ]; then
    aliasman_path="$script_dir/aliasmanager.sh"
  else
    aliasman_path="$HOME/.aliasmanager/aliasmanager.sh"
  fi

  # Copy aliasmanager.sh to ~/.aliasmanager/ for persistence
  local aliasman_dst="$HOME/.aliasmanager/aliasmanager.sh"
  mkdir -p "$HOME/.aliasmanager"
  if [ -f "$aliasman_path" ]; then
    cp "$aliasman_path" "$aliasman_dst"
    ok "aliasmanager.sh copied to ~/.aliasmanager/"
  fi

  # Create symlink for CLI access
  local bindir="$HOME/.local/bin"
  mkdir -p "$bindir"
  if [ ! -f "$bindir/aliasmanager" ]; then
    ln -s "$aliasman_dst" "$bindir/aliasmanager"
    ok "Symlink created: $bindir/aliasmanager"
  fi

  # Write .zshrc (use temp file for safety)
  local zshrc_tmp
  zshrc_tmp="$(mktemp)"
  cat > "$zshrc_tmp" <<ZSHRCEOF
# ═══════════════════════════════════════════════════════════════
#  .zshrc — generated by zsh-setup.sh (main4-plasma)
#  ═══════════════════════════════════════════════════════════════

# Disable p10k config wizard (MUST be before the theme)
export POWERLEVEL9K_DISABLE_CONFIGURATION_WIZARD=true

# oh-my-zsh
source \$HOME/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme

# Source custom p10k config (MUST come after the theme)
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Source aliasmanager (standalone aliases + helper)
[[ ! -f "\$HOME/.aliasmanager/aliasmanager.sh" ]] || . "\$HOME/.aliasmanager/aliasmanager.sh"

# Source custom zsh config (PATH, env vars, history)
[ -f "\$HOME/.zshconfig" ] && . "\$HOME/.zshconfig"
ZSHRCEOF
  mv "$zshrc_tmp" "$HOME/.zshrc"
  ok "~/.zshrc created"

  # ── 5. Generate .zshconfig ─────────────────────────────────
  echo ""
  info "Setting up ~/.zshconfig..."

  # Backup only if exists
  if [ -f "$HOME/.zshconfig" ]; then
    local ts
    ts="$(date +%Y%m%d-%H%M%S)"
    local bak2="$HOME/.zshconfig.bak.$ts"
    cp "$HOME/.zshconfig" "$bak2"
    warn "Backed up existing .zshconfig -> $bak2"
  fi

  # Write .zshconfig (use temp file for safety)
  local zshcfg_tmp
  zshcfg_tmp="$(mktemp)"
  cat > "$zshcfg_tmp" <<ZSHEOF
# ═══════════════════════════════════════════════════════════════
#  .zshconfig — custom ZSH configuration
#  ═══════════════════════════════════════════════════════════════
#  Generated by zsh-setup.sh (main4-plasma)
#  NOTE: Aliases live in aliasmanager.sh — not here.

# --- PATH -------------------------------------------------------
export PATH="\$HOME/.local/bin:\$HOME/bin:\$PATH"

# --- Editors ----------------------------------------------------
export EDITOR="nvim"

# --- Browser ----------------------------------------------------
export BROWSER="chrome"
export CHROME_EXECUTABLE="/usr/bin/google-chrome-stable"

# --- Flutter SDK ------------------------------------------------
export PATH="\$PATH:\$HOME/flutter/bin"
export FLUTTER_ROOT="\$HOME/flutter"

# --- Android SDK ------------------------------------------------
export ANDROID_HOME="\$HOME/Android/Sdk"
export PATH="\$PATH:\$ANDROID_HOME/platform-tools"
export PATH="\$PATH:\$ANDROID_HOME/tools"
export PATH="\$PATH:\$ANDROID_HOME/tools/bin"
export PATH="\$PATH:\$ANDROID_HOME/emulator"

# --- Shortcuts --------------------------------------------------
export cfg="\$HOME/.config"

# --- History ----------------------------------------------------
HISTFILE=\$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
ZSHEOF
  mv "$zshcfg_tmp" "$HOME/.zshconfig"
  ok "~/.zshconfig created"

  # ── 6. Change default shell ────────────────────────────────
  echo ""
  info "Changing default shell to ZSH..."
  if [ "$SHELL" = "$(which zsh)" ]; then
    ok "Default shell is already ZSH"
  else
    if [ "${1:-}" = "--yes" ]; then
      chsh -s "$(which zsh)" 2>/dev/null && ok "Default shell changed to ZSH"
    else
      if prompt_yes "Change default shell to ZSH? (log out/in to apply)" "y"; then
        chsh -s "$(which zsh)" 2>/dev/null && ok "Default shell changed to ZSH"
      else
        info "Skipping shell change"
      fi
    fi
  fi

  # ── 7. Done ────────────────────────────────────────────────
  echo ""
  echo "╔══════════════════════════════════════════════════════╗"
  echo "║            ZSH Setup Complete!                      ║"
  echo "╠══════════════════════════════════════════════════════╣"
  echo "║  Next steps:                                        ║"
  echo "║  1. Restart your terminal or run: exec zsh          ║"
  echo "║  2. Run: helper      to see all aliases             ║"
  echo "║  3. Or customize:    ~/.zshconfig                   ║"
  echo "╚══════════════════════════════════════════════════════╝"

  state_mark "zsh_setup"
}

# ─── State tracking ─────────────────────────────────
STATE_FILE="$HOME/.aliasmanager/setup-state.txt"
state_done() { mkdir -p "$HOME/.aliasmanager"; grep -qx "$1=done" "$STATE_FILE" 2>/dev/null; }
state_mark() { mkdir -p "$HOME/.aliasmanager"; sed -i "/^$1=/d" "$STATE_FILE" 2>/dev/null; echo "$1=done" >> "$STATE_FILE"; }

# ═══════════════════════════════════════════════════════════════════
#  MAIN
#  ═══════════════════════════════════════════════════════════════════

case "${1:-}" in
  --help|-h)
    echo "Usage: bash zsh-setup.sh [--yes]"
    echo "  --yes    Run non-interactively (auto-approve all)"
    exit 0
    ;;
  *)
    setup_zsh "${1:-}"
    ;;
esac
