#!/bin/bash
# ═══════════════════════════════════════════════════════════════════
#  zsh-setup — ZSH + oh-my-zsh + powerlevel10k bootstrapper
#  ═══════════════════════════════════════════════════════════════════
#  Installs and configures a complete ZSH environment:
#    - ZSH shell (via pacman)
#    - oh-my-zsh framework
#    - powerlevel10k theme
#    - ~/.zshrc (sources aliasmanager.sh + .zshconfig)
#    - ~/.zshconfig (PATH, EDITOR, HISTORY, env vars)
#
#  USAGE:
#    bash zsh-setup.sh              # Run interactively
#    bash zsh-setup.sh --yes        # Run non-interactively
#    bash zsh-setup.sh --help       # Show help
#
#  NOTE: All aliases live in aliasmanager.sh — NOT in .zshconfig.
#  ═══════════════════════════════════════════════════════════════════

set -euo pipefail

# ─── Colors ──────────────────────────────────────────────────────
R='\033[0;31m' G='\033[0;32m' Y='\033[1;33m' C='\033[0;36m'
B='\033[1;37m' N='\033[0m'

info()  { echo -e "  ${C}ℹ️${N}  $1"; }
ok()    { echo -e "  ${G}✅${N} $1"; }
warn()  { echo -e "  ${Y}⚠️${N}  $1"; }
fail()  { echo -e "  ${R}❌${N} $1"; }

prompt_yes() {
  local d="${2:-y}"
  read -p "  ${1} [${d}]: " r; r="${r:-$d}"
  [[ "$r" == "y" || "$r" == "Y" || "$r" == "yes" ]]
}

# ═══════════════════════════════════════════════════════════════════
#  ZSH-SETUP
#  ═══════════════════════════════════════════════════════════════════

setup_zsh() {
  echo ""
  echo "╔══════════════════════════════════════════════════════╗"
  echo "║            ZSH Setup — main4-plasma                 ║"
  echo "╚══════════════════════════════════════════════════════╝"

  # ── 1. Install ZSH ─────────────────────────────────────────
  echo ""
  info "Installing ZSH..."
  if command -v zsh &>/dev/null; then
    ok "ZSH already installed ($(zsh --version 2>/dev/null | head -1))"
  else
    sudo pacman -S --noconfirm zsh 2>&1 | tail -1
    ok "ZSH installed"
  fi

  # ── 2. Install oh-my-zsh ───────────────────────────────────
  echo ""
  info "Setting up oh-my-zsh..."
  if [ -d "$HOME/.oh-my-zsh" ]; then
    ok "oh-my-zsh already installed"
  else
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended 2>/dev/null
    if [ -d "$HOME/.oh-my-zsh" ]; then
      ok "oh-my-zsh installed"
    else
      fail "oh-my-zsh installation failed"
      return 1
    fi
  fi

  # ── 3. Install powerlevel10k ───────────────────────────────
  echo ""
  info "Setting up powerlevel10k theme..."
  local p10k_dir="$HOME/.oh-my-zsh/custom/themes/powerlevel10k"
  if [ -d "$p10k_dir" ]; then
    ok "powerlevel10k already installed"
  else
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "$p10k_dir" 2>/dev/null
    if [ -d "$p10k_dir" ]; then
      ok "powerlevel10k installed"
    else
      warn "powerlevel10k installation failed — skipping"
    fi
  fi

  # ── 4. Generate .zshrc ─────────────────────────────────────
  echo ""
  info "Setting up ~/.zshrc..."
  if [ -f "$HOME/.zshrc" ]; then
    if [ "${1:-}" != "--yes" ]; then
      if prompt_yes "Existing .zshrc found. Back it up and overwrite?" "y"; then
        local bak="$HOME/.zshrc.bak.$(date +%Y%m%d-%H%M%S)"
        cp "$HOME/.zshrc" "$bak"
        warn "Backed up → $bak"
      else
        info "Skipping .zshrc — ensure it sources aliasmanager.sh and .zshconfig"
        return 0
      fi
    else
      local bak="$HOME/.zshrc.bak.$(date +%Y%m%d-%H%M%S)"
      cp "$HOME/.zshrc" "$bak"
      warn "Backed up existing .zshrc → $bak"
    fi
  fi

  # Find aliasmanager.sh relative to this script
  local aliasman_path
  local script_dir
  script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  if [ -f "$script_dir/aliasmanager.sh" ]; then
    aliasman_path="$script_dir/aliasmanager.sh"
  else
    aliasman_path="$HOME/.aliasmanager/aliasmanager.sh"
  fi

  cat > "$HOME/.zshrc" <<ZSHRCEOF
# ═══════════════════════════════════════════════════════════════
#  .zshrc — generated by zsh-setup.sh (main4-plasma)
#  ═══════════════════════════════════════════════════════════════

# Disable p10k config wizard on first load
POWERLEVEL10K_DISABLE_CONFIGURATION_WIZARD=true

# oh-my-zsh
source \$HOME/.oh-my-zsh/custom/themes/powerlevel10k/powerlevel10k.zsh-theme

# Source aliasmanager (standalone aliases + helper)
. "$aliasman_path"

# Source custom zsh config (PATH, env vars, history)
[ -f "\$HOME/.zshconfig" ] && . "\$HOME/.zshconfig"
ZSHRCEOF
  ok "~/.zshrc created"

  # ── 5. Generate .zshconfig ─────────────────────────────────
  echo ""
  info "Setting up ~/.zshconfig..."

  # Backup if exists
  if [ -f "$HOME/.zshconfig" ]; then
    local bak2="$HOME/.zshconfig.bak.$(date +%Y%m%d-%H%M%S)"
    cp "$HOME/.zshconfig" "$bak2"
    warn "Backed up existing .zshconfig → $bak2"
  fi

  cat > "$HOME/.zshconfig" <<ZSHEOF
# ═══════════════════════════════════════════════════════════════
#  .zshconfig — custom ZSH configuration
#  ═══════════════════════════════════════════════════════════════
#  Generated by zsh-setup.sh (main4-plasma)
#  NOTE: Aliases live in aliasmanager.sh — not here.

# ─── PATH ─────────────────────────────────────────────────────
export PATH="\$HOME/.local/bin:\$HOME/bin:\$PATH"

# ─── Editors ──────────────────────────────────────────────────
export EDITOR="nvim"

# ─── Browser ──────────────────────────────────────────────────
export BROWSER="chrome"
export CHROME_EXECUTABLE="/usr/bin/google-chrome-stable"

# ─── Shortcuts ────────────────────────────────────────────────
export cfg="\$HOME/.config"

# ─── History ──────────────────────────────────────────────────
HISTFILE=\$HOME/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
ZSHEOF
  ok "~/.zshconfig created"

  # ── 6. Change default shell ────────────────────────────────
  echo ""
  info "Changing default shell to ZSH..."
  if [ "$SHELL" = "$(which zsh)" ]; then
    ok "Default shell is already ZSH"
  else
    if [ "${1:-}" = "--yes" ]; then
      chsh -s "$(which zsh)" 2>/dev/null && ok "Default shell changed to ZSH"
    else
      if prompt_yes "Change default shell to ZSH? (log out/in to apply)" "y"; then
        chsh -s "$(which zsh)" 2>/dev/null && ok "Default shell changed to ZSH"
      else
        info "Skipping shell change — run manually: chsh -s \$(which zsh)"
      fi
    fi
  fi

  # ── 7. Done ────────────────────────────────────────────────
  echo ""
  echo "╔══════════════════════════════════════════════════════╗"
  echo "║            ZSH Setup Complete!                      ║"
  echo "╠══════════════════════════════════════════════════════╣"
  echo "║  Next steps:                                        ║"
  echo "║  1. Restart your terminal or run: exec zsh          ║"
  echo "║  2. Run: helper      to see all aliases             ║"
  echo "║  3. Or customize:    ~/.zshconfig                   ║"
  echo "╚══════════════════════════════════════════════════════╝"

  state_mark "zsh_setup"
}

# ─── State tracking (simple) ─────────────────────────────────
STATE_FILE="$HOME/.aliasmanager/setup-state.txt"
state_done() { mkdir -p "$HOME/.aliasmanager"; grep -qx "$1=done" "$STATE_FILE" 2>/dev/null; }
state_mark() { mkdir -p "$HOME/.aliasmanager"; sed -i "/^$1=/d" "$STATE_FILE" 2>/dev/null; echo "$1=done" >> "$STATE_FILE"; }

# ═══════════════════════════════════════════════════════════════
#  MAIN
#  ═══════════════════════════════════════════════════════════════

case "${1:-}" in
  --help|-h)
    echo "Usage: bash zsh-setup.sh [--yes]"
    echo "  --yes    Run non-interactively (auto-approve all)"
    exit 0
    ;;
  *)
    setup_zsh "${1:-}"
    ;;
esac
