version: "3"
services:
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Kolkata
      - URL=netajisubhash.duckdns.org
      - SUBDOMAINS=www,filebrowser,transmission,pihole,heimdall
      - VALIDATION=http
      - CERTPROVIDER=zerossl
      - PROPAGATION= #optional
      - DUCKDNSTOKEN=2ac0abab-29fe-4259-ad50-50b4c8702720
      - EMAIL=amarjithraveendran@gmail.com
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS=
      - STAGING=false #optional
      - MAXMINDDB_LICENSE_KEY= #optional
    volumes:
      - ./config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
 
    networks:
      - intranet


networks:
  intranet:
    name: intra_network
    ipam:
      driver: default
      config:
        - subnet: 10.2.5.0/24


#networks:
#  my-proxy-net:
#    external:
#      name: wirehole_private_network     

