#!/bin/bash
shopt -s extglob

function powermenu {

options="Cancel\nShutdown\nRestart\nLock"
selected=$(echo -e $options | dmenu)

# just [[$selected="shutdown"]] to [[ $selected="shutdown" ]] fixed a big error hurting you

if [[ $selected = "Shutdown" ]]; then
  poweroff
elif [[ $selected = "Restart" ]]; then
  reboot
elif [[ $selected = "Logout" ]]; then
  return
elif [[ $selected = "Lock" ]]; then
  return
fi


}

powermenu
