#!/bin/bash
if ! command -v zenity &> /dev/null; then
    echo "Zenity is not installed. Installing it using pacman..."
    sudo pacman -S --noconfirm zenity
fi





#output="/home/starbackend/Videos"
playlist="--yes-playlist"
#quality="360"
#url="https://www.youtube.com/watch?v=j-7JQt5m_v0"

onlyaudio=""
read -p "enter url: " url
read -p "Is it audio only y/n : " isAudioOnly


if [ "$isAudioOnly" == "y" ]; then
  onlyaudio="--extract-audio --audio-format m4a"
  quality="144"
elif [ "$isAudioOnly" == "n" ]; then
  onlyaudio=""
  read -p "Quality (360, 480, 720, 1080): " quality
else
  echo "What you entered is invalid"
fi


echo "select a folder to download files ------------------"
# Prompt the user to select a folder using Zenity
selected_folder=$(zenity --file-selection --directory --title="Select a Folder")


# Check if the user canceled folder selection
if [ $? -eq 1 ]; then
    echo "Folder selection canceled."
    exit 1
fi


#read -p "enter folder to save : /home/$USER/ already there : " output

#output="/home/$USER/$output"

cmd="yt-dlp -o '$selected_folder/%(playlist_index)s-%(title)s.%(ext)s' -f 'bestaudio[height<=$quality]+best[ext=mp4]/best[ext=mp4]' $playlist '$url' $onlyaudio"

eval $cmd
