version: "2.1"
services:
  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=1000 #optional
      - PGID=1000 #optional
      - TZ=Asia/Kolkata
      - SUBDOMAINS=ec4.duckdns.org
      - TOKEN=175927cc-4e5b-41bf-b3c8-44322d94575d
      - LOG_FILE=false #optional
    volumes:
      - ./duckdns:/config #optional
    restart: unless-stopped

  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - URL=ec4.duckdns.org
      # - VALIDATION=dns
      - CERTPROVIDER=zerossl #optional
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=175927cc-4e5b-41bf-b3c8-44322d94575d
      - EMAIL=sonunigam4097@gmail.com #optional
      - ONLY_SUBDOMAINS=false #optional
      #- EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - ./swag:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
    networks:
      - zombie


networks:
  zombie:
    name: zombie
    ipam:
      driver: default
      config:
        - subnet: 10.2.5.0/24 