#! /bin/sh

pkill -x sxhkd ; sxhkd -c ~/.config/sxhkd/bspwm-sxhdrc ~/.config/sxhkd/alone-sxhkdrc &
pkill -x polybar ; polybar &


bspc monitor -d 1 2 3 4 5 6 7 8 9


bspc config top_padding 30



bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a realvnc-vncserverui-service hidden=on
#RealVNC Server 

bspc rule -a kdeconnect.app state=floating

bash ~/basescripts/utilities/autostart.sh &
feh --bg-fill ~/Downloads/shame1.png
kdeconnect-cli -l &
