#! /bin/sh


bash ~/basescripts/utilities/autostarts/bspwm-autostart-7300u.sh

bspc config gapless_monocle false
bspc monitor -d 1 2 3 4 5 6 7 8 9


bspc config top_padding 30
bspc config normal_border_color #FFFFFF 



bspc config border_width         4
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true 

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a realvnc-vncserverui-service hidden=on
#RealVNC Server 
bspc rule -a crx_nhnkgkmpokjdijjlfcknhephafdopocl state=floating
bspc rule -a kdeconnect.app state=floating
bash ~/basescripts/utilities/autostart.sh &
kdeconnect-cli -l &

feh --recursive --bg-fill --randomize ~/.wallpapers &
watcher --start & 
xfce4-power-manager &
nm-applet &



bash ~/basescripts/utilities/livewall.sh &
