#! /bin/sh



bspc config gapless_monocle false
bspc monitor -d 1 2 3 4 5  


bspc config top_padding 0

bspc config normal_border_color "#484848"
bspc config focused_border_color "#FFFFFF"
bspc config urgent_border_color "#B58900"
bspc config presel_border_color "#FFFFFF"



bspc config border_width         2
bspc config window_gap          20

bspc config split_ratio          0.52
bspc config borderless_monocle   true 

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a realvnc-vncserverui-service hidden=on
#RealVNC Server 
bspc rule -a kdeconnect.app state=floating
bspc rule -a Thunar state=floating
bspc rule -a Blueman-manager state=floating
bspc rule -a pavucontrol state=floating


bspc rule -a firepad sticky=on state=fullscreen border=0 margin=0 rectangle=1920x1080+0+0
bspc rule -a padterm sticky=on state=floating border=0 margin=0 rectangle=1920x1080+0+0

bash ~/basescripts/utilities/autostart.sh &




