#!/bin/bash
declare -a options=(

"FHcodeCamp"
"srisri"
"DistroTube"
"MohitTyagi"
"physicsgalaxy74"
"quit"

)

# The combination of echo and printf is done to add line breaks to the end of each
# item in the array before it is piped into dmenu.  Otherwise, all the items are listed
# as one long line (one item).

choice=$(echo "$(printf '%s\n' "${options[@]}")" | rofi -dmenu -i )
# Ultimately, what do want to do with our choice?  Open in our editor!


if [ $choice = "quit" ]
then
   exit 1
else
   chromium "www.youtube.com/c/$choice"
fi




