#!/bin/bash

sudo pacman -S --noconfirm \
        rofi mupdf npm xclip scrot neofetch htop ranger python-pip zenity gnome-tweaks qbittorrent cheese kdeconnect dmenu sxhkd redshift  \
        kitty feh gparted rust ttf-firacode-nerd neovim ttf-fira-code archlinux-keyring\
        zsh powerline-fonts base-devel docker docker-compose polybar vim bspwm \
        ttf-jetbrains-mono ttf-jetbrains-mono-nerd ttf-roboto tree xprintidle


# echo 'alias vi="nvim"' >> ~/.bashrc
# echo 'alias vim="nvim"' >> ~/.bashr
# echo 'alias vim="nvim"' >> ~/.zshrc 
