#!/bin/zsh

# Set source and destination directories
SOURCE_DIR="$HOME/basescripts/bin"
DEST_DIR="$HOME/bin"

# Create ~/bin if it doesn't exist
mkdir -p "$DEST_DIR"

# Move files from SOURCE_DIR to DEST_DIR
echo "Moving files from $SOURCE_DIR to $DEST_DIR..."
mv "$SOURCE_DIR"/* "$DEST_DIR"

# Check if ~/bin is in PATH
if ! grep -qF "$DEST_DIR" "$HOME/.zshrc"; then
    # Add ~/bin to PATH in .zshrc
    echo "Adding $DEST_DIR to PATH..."
    echo "export PATH=\$PATH:$DEST_DIR" >> "$HOME/.zshrc"
fi

# Reload the .zshrc file
echo "Reloading .zshrc file..."
source "$HOME/.zshrc"


# Path to your .zshrc file
zshrc_path="$HOME/.zshrc"

# Check if the source line for aliases is already present
if grep -q "source ~/basescripts/aliases" "$zshrc_path"; then
    echo "The source line for aliases is already present in $zshrc_path."
else
    # Add the source line for aliases to .zshrc
    echo "Adding the source line for aliases to $zshrc_path..."
    echo "source ~/bin/aliases" >> "$zshrc_path"
    echo "The source line for aliases has been added."
fi
