#!/bin/bash


sudo pacman -S neovim ttf-jetbrains-mono ttf-jetbrains-mono-nerd --noconfirm
# Set up Neovim configuration
mkdir -p ~/.config/nvim
git clone https://github.com/NvChad/NvChad ~/.config/nvim --depth 1
nvim 

